# Generated by Django 5.2.17 on 2026-10-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('laytime_allowed_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('demurrage_rate_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('despatch_rate_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disclaimer', models.TextField(default='虚构租约条款，仅用于演示计时与费用核算，不构成法律解释或建议。')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('FINAL', '已定稿'), ('BLOCKED', '无法起算')], default='FINAL', max_length=10)),
                ('natural_hours', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('laytime_used_hours', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('actual_working_hours', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('allowed_hours', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('demurrage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('despatch_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('segments', models.JSONField(default=list)),
                ('pending_fragment_ids', models.JSONField(default=list)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('disclaimer', models.TextField(default='虚构租约条款下的演示性核算，不构成法律解释或建议。')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEMURRAGE', '滞期费'), ('DESPATCH', '速遣费'), ('INFO', '说明')], max_length=10)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('basis_hours', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clause_codes', models.JSONField(default=list)),
                ('intervals', models.JSONField(default=list)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='laytime.settlement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('vessel_name', models.CharField(max_length=120)),
                ('port', models.CharField(max_length=120)),
                ('charter_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laytime.charterparty')),
            ],
        ),
        migrations.AddField(
            model_name='settlement',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='laytime.voyage'),
        ),
        migrations.CreateModel(
            name='EventFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ARRIVAL', '抵港'), ('NOR_TENDERED', 'NOR 送达'), ('NOR_ACCEPTED', 'NOR 被接受'), ('STOPPAGE_START', '停工开始'), ('STOPPAGE_END', '复工'), ('COMPLETION', '装卸完毕')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, choices=[('', '—'), ('WEATHER', '天气'), ('BERTH_WAIT', '等待泊位'), ('OTHER', '其他')], default='', max_length=20)),
                ('evidence_status', models.CharField(choices=[('VERIFIED', '已核实'), ('PENDING', '待核对')], default='VERIFIED', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='laytime.voyage')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('rule_type', models.CharField(choices=[('WEEKEND_EXCLUSION', '周末不计入'), ('WEATHER_EXCLUSION', '天气停工不计入'), ('BERTH_WAIT_EXCLUSION', '等泊时间不计入'), ('NOR_ACCEPTANCE', 'NOR 被接受方起算'), ('NO_DOUBLE_COUNT', '重叠原因不重复扣减'), ('EVIDENCE_REQUIRED', '缺证据片段待核对')], max_length=40)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('charter_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='laytime.charterparty')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('charter_party', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('voyage', 'version')},
        ),
    ]
