# Generated by Django 5.2.17 on 2026-10-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='租约代码')),
                ('name', models.CharField(max_length=200, verbose_name='租约名称')),
                ('fictional_notice', models.TextField(default='本租约条款为演示用虚构规则，不替代任何真实合同文本或法律解释。', verbose_name='虚构规则声明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='航次编号')),
                ('vessel_name', models.CharField(max_length=100, verbose_name='船名')),
                ('port_name', models.CharField(max_length=100, verbose_name='港口')),
                ('cargo_description', models.CharField(blank=True, max_length=200, verbose_name='货物')),
                ('operation', models.CharField(choices=[('LOAD', '装货'), ('DISCHARGE', '卸货')], default='DISCHARGE', max_length=10, verbose_name='作业')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charter_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='laytime.charterparty')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='条款编号')),
                ('clause_type', models.CharField(choices=[('LAYTIME_ALLOWED', '允许装卸时间'), ('TURNTIME', '起算准备时间'), ('EXCLUSION', '时间排除'), ('DEMURRAGE_RATE', '滞期费率'), ('DESPATCH_RATE', '速遣费率'), ('ONCE_ON_DEMURRAGE', '一旦滞期持续滞期')], max_length=30, verbose_name='条款类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('text', models.TextField(verbose_name='条款原文（虚构）')),
                ('params', models.JSONField(default=dict, verbose_name='结构化参数')),
                ('charter_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='laytime.charterparty')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('charter_party', 'code'), name='uniq_clause_code_per_cp')],
            },
        ),
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('WEATHER', '恶劣天气'), ('WEEKEND_HOLIDAY', '周末/节假日'), ('WAITING_BERTH', '等待泊位'), ('EQUIPMENT', '船舶设备故障'), ('STRIKE', '罢工'), ('OTHER', '其他')], max_length=20, verbose_name='停工原因')),
                ('started_at', models.DateTimeField(verbose_name='开始(UTC)')),
                ('ended_at', models.DateTimeField(verbose_name='结束(UTC)')),
                ('evidence_status', models.CharField(choices=[('VERIFIED', '已核实'), ('PENDING', '待核对'), ('DISPUTED', '有争议')], default='PENDING', max_length=10, verbose_name='证据状态')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='证据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoppages', to='laytime.voyage')),
            ],
            options={
                'ordering': ['started_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='stoppage_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('FINAL', '已定稿'), ('SUPERSEDED', '已被取代')], default='DRAFT', max_length=12, verbose_name='状态')),
                ('report', models.JSONField(verbose_name='计算快照')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='结算总额')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='币种')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='定稿时间')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='laytime.voyage')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('voyage', 'version'), name='uniq_settlement_version')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ARRIVAL', '抵港'), ('NOR_TENDERED', '准备就绪通知送达'), ('NOR_ACCEPTED', '准备就绪通知被接受'), ('BERTHED', '靠泊'), ('COMMENCED', '开始作业'), ('COMPLETED', '完工'), ('DEPARTED', '离港')], max_length=20, verbose_name='事件')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间(UTC)')),
                ('evidence_status', models.CharField(choices=[('VERIFIED', '已核实'), ('PENDING', '待核对'), ('DISPUTED', '有争议')], default='PENDING', max_length=10, verbose_name='证据状态')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='证据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='laytime.voyage')),
            ],
            options={
                'ordering': ['occurred_at'],
                'constraints': [models.UniqueConstraint(fields=('voyage', 'event_type'), name='uniq_event_type_per_voyage')],
            },
        ),
    ]
